<a href="https://colab.research.google.com/github/boadt/R/blob/main/R_%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D_1_(20230309).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

/#create=true&language=R

In [1]:
x<-c(1,2,3,4,5,6,7,8,9)
A<-matrix(x, nrow=3, ncol=3)

In [2]:
A

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [ ]:
B<-matrix(x, nrow=3, ncol=3, byrow=T)
B

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [ ]:
xx<-c(1,2,3,4,5,6)
arr<-array(xx, dim=c(2,2,3))
arr[ , ,1]

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [ ]:
ID<-c(1,2,3,4,5,6,7,8,9,10)
SEX<-c("F","F","M","M","F","F","M","F","F","M")
AGE<-c(30,23,25,56,54,43,37,43,34,34)
AREA<-c("제주","서울","서울","경기","제주","인천","경기","인천","제주","제주")

f<- data.frame(ID,SEX,AGE,AREA)
f

ID SEX AGE AREA
1   1 F   30  제주
2   2 F   23  서울
3   3 M   25  서울
4   4 M   56  경기
5   5 F   54  제주
6   6 F   43  인천
7   7 M   37  경기
8   8 F   43  인천
9   9 F   34  제주
10 10 M   34  제주

In [ ]:
str(f)

'data.frame':	10 obs. of  4 variables:
 $ ID  : num  1 2 3 4 5 6 7 8 9 10
 $ SEX : chr  "F" "F" "M" "M" ...
 $ AGE : num  30 23 25 56 54 43 37 43 34 34
 $ AREA: chr  "제주" "서울" "서울" "경기" ...


In [ ]:
f$AGE

[1] 30 23 25 56 54 43 37 43 34 34

In [ ]:
str(ID)

 num [1:10] 1 2 3 4 5 6 7 8 9 10


In [ ]:
str(AGE)

 num [1:10] 30 23 25 56 54 43 37 43 34 34


In [ ]:
str(AREA)

 chr [1:10] "제주" "서울" "서울" "경기" "제주" "인천" "경기" "인천" "제주" ...


In [ ]:
mode(ID)

[1] "numeric"

In [ ]:
mode(AREA)

[1] "character"

In [ ]:
b<-c(TRUE,FALSE)
mode(b)

[1] "logical"

In [ ]:
frute<-c("apple","banana","banana","cherry","apple","banana","cherry","cherry","apple","apple")
frute<-factor(frute, labels = c("apple","banana","cherry"))
str(frute)

 Factor w/ 3 levels "apple","banana",..: 1 2 2 3 1 2 3 3 1 1


In [ ]:
f$SEX<-factor(SEX, labels = c("F","M"))
str(f$SEX)

 Factor w/ 2 levels "F","M": 1 1 2 2 1 1 2 1 1 2


In [ ]:
f$AREA<-factor(AREA, labels = c("서울","경기","제주","인천"))
str(f$AREA)

 Factor w/ 4 levels "서울","경기",..: 4 2 2 1 4 3 1 3 4 4


In [ ]:
x<- 1:10
y <- 10:1

print(x)
y

 [1]  1  2  3  4  5  6  7  8  9 10


[1] 10  9  8  7  6  5  4  3  2  1

In [ ]:
a<-10
if(a %% 2 == 0)
{print("짝수")}else{print("홀수")}


[1] "짝수"


In [ ]:
b<-1
c<-2
d<-3

if (b>c&b>d){
  print(b)
}else if(c>d&c>b)
  {print(c)}else
    {print(d)}

[1] 3


In [ ]:
#2단출력
a<-2

for(i in 1:9){
  sol<-(a*i)
  print(sol)
}

[1] 2
[1] 4
[1] 6
[1] 8
[1] 10
[1] 12
[1] 14
[1] 16
[1] 18


In [ ]:
for(i in 1:100){
  sum<-i
  sol<-sum+i
  print(sol)
}

[1] 2
[1] 4
[1] 6
[1] 8
[1] 10
[1] 12
[1] 14
[1] 16
[1] 18
[1] 20
[1] 22
[1] 24
[1] 26
[1] 28
[1] 30
[1] 32
[1] 34
[1] 36
[1] 38
[1] 40
[1] 42
[1] 44
[1] 46
[1] 48
[1] 50
[1] 52
[1] 54
[1] 56
[1] 58
[1] 60
[1] 62
[1] 64
[1] 66
[1] 68
[1] 70
[1] 72
[1] 74
[1] 76
[1] 78
[1] 80
[1] 82
[1] 84
[1] 86
[1] 88
[1] 90
[1] 92
[1] 94
[1] 96
[1] 98
[1] 100
[1] 102
[1] 104
[1] 106
[1] 108
[1] 110
[1] 112
[1] 114
[1] 116
[1] 118
[1] 120
[1] 122
[1] 124
[1] 126
[1] 128
[1] 130
[1] 132
[1] 134
[1] 136
[1] 138
[1] 140
[1] 142
[1] 144
[1] 146
[1] 148
[1] 150
[1] 152
[1] 154
[1] 156
[1] 158
[1] 160
[1] 162
[1] 164
[1] 166
[1] 168
[1] 170
[1] 172
[1] 174
[1] 176
[1] 178
[1] 180
[1] 182
[1] 184
[1] 186
[1] 188
[1] 190
[1] 192
[1] 194
[1] 196
[1] 198
[1] 200


In [7]:
#1

a<-1
b<-2
c<-3

if (a>b&a>c){
  print(a)
}else if (b>a&b>c){
    print(b)
}else {print(c)}


[1] 3


In [8]:
#2

a<-1
b<-2
c<-3

if (a>b>c){
  print(a,b,c)
}
else if (a>c>b){
  print(a,c,b)
}
else if (b>a>c){
  print(b,a,c)
}
else if (b>c>a){
  print(b,c,a)
}
else if (c>a>b){
  print(c,a,b)
}
else{print(c,b,a)}


ERROR: ignored

In [11]:
#3

a<-2000

if(a%%100 == 0&a%%400 != 0){
  print("평년입니다.")
}else{print("윤년입니다.")}

[1] "윤년입니다."


In [12]:
#4

for(i in 2:9){
  for(j in 1:9){
    print(i*j)
  }
}

[1] 2
[1] 4
[1] 6
[1] 8
[1] 10
[1] 12
[1] 14
[1] 16
[1] 18
[1] 3
[1] 6
[1] 9
[1] 12
[1] 15
[1] 18
[1] 21
[1] 24
[1] 27
[1] 4
[1] 8
[1] 12
[1] 16
[1] 20
[1] 24
[1] 28
[1] 32
[1] 36
[1] 5
[1] 10
[1] 15
[1] 20
[1] 25
[1] 30
[1] 35
[1] 40
[1] 45
[1] 6
[1] 12
[1] 18
[1] 24
[1] 30
[1] 36
[1] 42
[1] 48
[1] 54
[1] 7
[1] 14
[1] 21
[1] 28
[1] 35
[1] 42
[1] 49
[1] 56
[1] 63
[1] 8
[1] 16
[1] 24
[1] 32
[1] 40
[1] 48
[1] 56
[1] 64
[1] 72
[1] 9
[1] 18
[1] 27
[1] 36
[1] 45
[1] 54
[1] 63
[1] 72
[1] 81


In [14]:
#5

sum<-0
for(i in 1:100){
  sum<-sum + i
}
print(sum)

[1] 5050


In [16]:
#6

mul<-1
for(i in 1:5){
  mul<-mul*i
}
print(mul)

[1] 120


In [20]:
#7


for(i in 1:100){
  if(i%%2 == 0){
      print("짝수입니다.")}
else{print("홀수입니다.")}
}

[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."
[1] "짝수입니다."
[1] "홀수입니다."

In [29]:
#8

for(i in 1:100){
  if(i%%5 ==0){print("5의 배수")
  }else{print("5의 배수가 아닙니다.")}}

[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아닙니다."
[1] "5의 배수"
[1] "5의 배수가 아닙니다."
[1] "5의 배수가 아

In [30]:
#9

for(i in 1:100){
  if(i%%2 ==0 & i%%3 == 0){
    print(i)
  }
}

[1] 6
[1] 12
[1] 18
[1] 24
[1] 30
[1] 36
[1] 42
[1] 48
[1] 54
[1] 60
[1] 66
[1] 72
[1] 78
[1] 84
[1] 90
[1] 96


In [31]:
#10

sum<-0
for(i in 1:100){
  sum<-sum + i
}
print(sum/100)

[1] 50.5
